/**
 * Writes `docs/dev/test-matrix.md`: every command and every option, and what exercises it — an
 * offline test that drove it through `run()`, or a written reason it is not tested offline.
 *
 *   pnpm test:matrix        # runs the suite, then this; fails on anything with neither
 *
 * "Drove it" is measured, not searched for: under vitest, each top-level command appends the parsed
 * command and the option names it was given to `coverage/argv.jsonl` (`src/program.ts`). Imports
 * from `dist/`, so it builds first.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import type { Command } from "commander"
import { createProgram } from "../dist/program.js"
import { UNTESTED } from "./test-matrix-untested.ts"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const log = join(root, "coverage", "argv.jsonl")
const page = join(root, "docs", "dev", "test-matrix.md")

if (!existsSync(log)) {
  console.error("no coverage/argv.jsonl — run the suite first (pnpm test:matrix does)")
  process.exit(1)
}

const seen = new Map<string, Set<string>>()
for (const line of readFileSync(log, "utf8").split("\n")) {
  if (!line) continue
  const { command, options } = JSON.parse(line) as { command: string; options: string[] }
  const known = seen.get(command) ?? new Set<string>()
  for (const option of options) known.add(option)
  seen.set(command, known)
}

const program = createProgram()
const runnable = (command: Command): boolean =>
  (command as unknown as { _actionHandler: unknown })._actionHandler != null
const pathOf = (command: Command): string => {
  const words: string[] = []
  for (let at: Command | null = command; at?.parent; at = at.parent) words.unshift(at.name())
  return words.join(" ")
}

interface Row {
  command: string
  option?: string
  state: "tested" | "untested" | "missing"
  note: string
}

const untested = (command: string, option?: string) =>
  UNTESTED.find(
    (entry) =>
      (entry.command === command || (entry.command.endsWith(" *") && command.startsWith(entry.command.slice(0, -1)))) &&
      entry.option === option,
  )

const rows: Row[] = []
const walk = (command: Command): void => {
  if (command.parent && runnable(command)) {
    const path = pathOf(command)
    const ran = seen.get(path)
    const skip = untested(path)
    rows.push(
      ran
        ? { command: path, state: "tested", note: "" }
        : skip
          ? { command: path, state: "untested", note: skip.reason }
          : { command: path, state: "missing", note: "" },
    )
    for (const option of command.options) {
      const name = option.long ?? option.short ?? ""
      if (name === "--help") continue
      const optionSkip = untested(path, name) ?? (skip && !ran ? skip : undefined)
      rows.push(
        ran?.has(name)
          ? { command: path, option: name, state: "tested", note: "" }
          : optionSkip
            ? { command: path, option: name, state: "untested", note: optionSkip.reason }
            : { command: path, option: name, state: "missing", note: "" },
      )
    }
  }
  for (const child of command.commands) walk(child)
}
walk(program)

const globalOptions = program.options.filter((option) => option.long && option.long !== "--help")
const globalSeen = new Set([...seen.values()].flatMap((options) => [...options]))
for (const option of globalOptions) {
  const name = option.long as string
  const skip = untested("", name)
  rows.push(
    globalSeen.has(name)
      ? { command: "", option: name, state: "tested", note: "" }
      : skip
        ? { command: "", option: name, state: "untested", note: skip.reason }
        : { command: "", option: name, state: "missing", note: "" },
  )
}

const stale = UNTESTED.filter(
  (entry) =>
    !rows.some(
      (row) =>
        row.option === entry.option &&
        (row.command === entry.command ||
          (entry.command.endsWith(" *") && row.command.startsWith(entry.command.slice(0, -1)))),
    ),
)

const MARK = { tested: "✅", untested: "⛔", missing: "❌" } as const
const count = (state: Row["state"]) => rows.filter((row) => row.state === state).length
const cell = (text: string) => text.replace(/\|/g, "\\|")

writeFileSync(
  page,
  `<!-- Generated by scripts/test-matrix.ts from the command tree and a test run. Do not edit; \`pnpm test:matrix\`. -->

# Test matrix

Every command and option of \`tg\`, and whether an offline test drives it through the CLI. ✅ a test
ran it · ⛔ not tested offline, with the reason and where it is checked instead · ❌ nothing.
Measured from the test run (\`coverage/argv.jsonl\`), not searched for — see
[TESTING.md](TESTING.md) for how, and for the states and failures that cut across commands.

**${count("tested")} ✅ · ${count("untested")} ⛔ · ${count("missing")} ❌** — ${rows.filter((row) => !row.option).length} commands, ${rows.filter((row) => row.option).length} options.

| Command | Option | | Note |
|---|---|---|---|
${rows
  .map(
    (row) =>
      `| ${row.command ? `\`${row.command}\`` : "*global*"} | ${row.option ? `\`${row.option}\`` : ""} | ${MARK[row.state]} | ${cell(row.note)} |`,
  )
  .join("\n")}
`,
)

let failed = false
if (stale.length > 0) {
  failed = true
  console.error("untested entries that name nothing in the program any more:")
  for (const entry of stale) console.error(`  ${entry.command}${entry.option ? ` ${entry.option}` : ""}`)
}
const missing = rows.filter((row) => row.state === "missing")
if (missing.length > 0 && process.argv.includes("--check")) {
  failed = true
  console.error(`${missing.length} commands or options with no test and no reason — see docs/dev/test-matrix.md:`)
  for (const row of missing) console.error(`  ${row.command || "(global)"}${row.option ? ` ${row.option}` : ""}`)
}
console.error(
  `test matrix: ${count("tested")} tested, ${count("untested")} untested with a reason, ${missing.length} missing`,
)
process.exit(failed ? 1 : 0)
